### ISSUE TITLE
学长，很多字体找不到。

### ISSUE THREAD

**Issue by imastere** [Frank17/jufe-theis-tex#2]
我这边是Mac，应该是我没装CJK，建议用一些通用字体。

**Comment by Les1ie** [comment]
用啥字体取决于学校的论文要求吧……
老老实实用`word`写吧 😂，这个模板 **BUG还挺多** ，图表排版、页边距啥的好像都和学校的还有点差距。
当然，如果你愿意修改这些存在的问题的话更好~
祝答辩顺利~

**Comment by imastere** [comment]
> 用啥字体取决于学校的论文要求吧……
> 老老实实用`word`写吧 😂，这个模板 **BUG还挺多** ，图表排版、页边距啥的好像都和学校的还有点差距。
> 当然，如果你愿意修改这些存在的问题的话更好~
> 祝答辩顺利~

**Comment by imastere** [comment]
配了两天环境还是各种bug，先老老实实用Word吧，等以后时间再搞一下～谢谢啦～～   ：）

**Comment by zipzou** [comment]
latex需要使用三个中文字体，在Mac中没有预装：[SimSun(宋体)](https://www.wfonts.com/download/data/2015/08/10/simsun/simsun.zip)、[SimHei(黑体)](https://www.wfonts.com/download/data/2014/06/01/simhei/simhei.zip)、[KaiTi(楷体)](https://www.wfonts.com/download/data/2016/07/15/kaiti/kaiti.zip)，安装完两个字体后就可正常使用。Windows可以不用安装，应该都有了。
整个模板为了支持中文，使用xelatex编译，因此需要指定xelatex编译器，默认的是pdflatex只能编译英文。配置项可以使用VSCode参考README，或者直接复制。
TexLive新版都包含了xeCJK，请依照demo: chinese.tex中，声明`\usepackage{xeCJK}`。
@imastere @Les1ie

**Comment by Les1ie** [comment]
提个建议，在使用`latex`前，最好征求下导师的建议，直接导出成PDF，后续可能不方便导师帮你检查一些格式上的问题。
> PS： 我去年经历了被要求`pdf`转`word`来检查和调整格式，直接带上痛苦面具 😂😂

**Comment by imastere** [comment]
哈哈～我这边在下载下这些字体，再试一下～论文我还是拿Word写了给导师，这个latex主要是想学一下，以后读研可能要用～

**Comment by imastere** [comment]
太棒了，确实是这些字体的原因，到网上下载了这些字体，能用了～～～太感谢了～～～作者太优秀了！！！
